// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJNfmC43qDcGCLPCvV0sJi9inTSX7tlBE',
    appId: '1:519107894617:web:e857a0d035813ea58ac048',
    messagingSenderId: '519107894617',
    projectId: 'firelamp-ea3fe',
    authDomain: 'firelamp-ea3fe.firebaseapp.com',
    storageBucket: 'firelamp-ea3fe.appspot.com',
    measurementId: 'G-2MWT1VXY2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxXZq3BziiOhMpLrw9MPT4Ucbw3UUdzHo',
    appId: '1:519107894617:android:fdb42b72cd6b9f3f8ac048',
    messagingSenderId: '519107894617',
    projectId: 'firelamp-ea3fe',
    storageBucket: 'firelamp-ea3fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuZ59u5Ryszy5W73g4GVeHxvqFNCytbNU',
    appId: '1:519107894617:ios:1d1f39861c5497a78ac048',
    messagingSenderId: '519107894617',
    projectId: 'firelamp-ea3fe',
    storageBucket: 'firelamp-ea3fe.appspot.com',
    iosBundleId: 'com.example.lampApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuZ59u5Ryszy5W73g4GVeHxvqFNCytbNU',
    appId: '1:519107894617:ios:15f8d0ffca8ad4948ac048',
    messagingSenderId: '519107894617',
    projectId: 'firelamp-ea3fe',
    storageBucket: 'firelamp-ea3fe.appspot.com',
    iosBundleId: 'com.example.lampApp.RunnerTests',
  );
}
